name: Code Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check codebase (lint and typecheck)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Installation
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: TypeCheck
        run: yarn run typecheck
